version: '2'

services:
  nginx:
    image: vtrgomes/nginx-alpine
    ports:
      - 80:80
    volumes_from:
      - app
    networks:
      - app2-network
    links:
      - app
      - php
      - mysql

  app:
    command: "true"
    image: alpine:latest
    volumes:
      - ./:/var/www/app
    links:
      - mysql
    networks:
      - app2-network

  php:
    image: vtrgomes/composer-alpine:7.4
    expose:
      - 9000
    volumes:
      - ./composer-cache:/composer/cache
    volumes_from:
      - app
    networks:
      - app2-network
    links:
      - mysql
      - redis

  redis:
    image: vtrgomes/redis-alpine
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - app2-network

  mysql:
    image: vtrgomes/mysql-57
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - app2-network

volumes:
  composer-cache:
    driver: local

networks:
  app2-network:
    driver: bridge
